services:
  mongodb:
    image: mongo:6
    container_name: chat-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  app:
    build: .
    container_name: chat-app
    ports:
      - "3000:10000"
    depends_on:
      - mongodb
    environment:
      NODE_ENV: development
      PORT: 10000
      MONGO_URI: mongodb://mongodb:27017/chat-app
      JWT_SECRET: n4R7pDk8qZ1sW5xY2vB3cV7tJ0mN8fH4K928
      JWT_EXPIRES: 7d
      ADMIN_EMAIL: admin@example.com
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: superStrongAdminPass123
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
      - /app/node_modules

volumes:
  mongodb_data: